# Generated by Django 4.0.4 on 2022-04-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oneplusmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mseries', models.CharField(max_length=30)),
                ('mname', models.CharField(max_length=50)),
                ('mprice', models.IntegerField()),
                ('mram', models.CharField(max_length=10)),
                ('mrom', models.CharField(max_length=10)),
                ('mpro', models.CharField(max_length=10)),
                ('mdesc', models.CharField(max_length=100)),
            ],
        ),
    ]
